import { Box } from '@mui/material';

import { Markdown } from 'src/components/markdown';

export default function NewsDetails() {
  return (
    <Box>
      <Markdown
        children={`<p>Beaton, 29 tuổi, nổi tiếng là "người giải mã các bí quyết tuyển sinh vào những đại học danh giá". Anh từng học tại <a class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineHover nml__editor__content__link css-lf1xlu" target="_blank" rel="dofollow" href="https://vnexpress.net/chu-de/dai-hoc-harvard-2280" node="[object Object]">Harvard </a>và giành học bổng ngành tiến sĩ chính sách công tại Đại học Oxford. Chàng trai này còn có hai bằng thạc sĩ tại Stanford, một về kinh doanh và một về công nghệ giáo dục, cùng nhiều bằng cấp khác từ Princeton, Yale và Đại học Thanh Hoa (Trung Quốc).</p>
<p>Thông điệp của Beaton gửi gắm học sinh khá ngắn gọn: Tối ưu hóa tuổi thơ bằng cách xây dựng kỹ năng và niềm đam mê từ trước khi vào cấp 3. Chiến lược là tập trung vào những lĩnh vực bạn xuất sắc nhất. Nếu không đạt thành tích cao trong hoạt động này, hãy từ bỏ và chuyển sang hoạt động khác.</p>
<p>"Một nền giáo dục tuyệt vời đã thay đổi cuộc đời tôi", Beaton, CEO kiêm đồng sáng lập Crimson Education, chia sẻ. "Nó cũng có thể thay đổi cuộc đời bạn".</p>
<span class="mnl__image__root nml__editor__content__image MuiBox-root css-1d2j38h" node="[object Object]"><span class="mnl__image__wrapper lazy-load-image-background blur lazy-load-image-loaded" style="color: transparent; display: inline-block;"><img class="MuiBox-root css-1d1z4yn" alt="Jamie Beaton, 29 tuổi, nhà sáng lập của Crimson Education, trung tâm luyện thi vào đại học hàng đầu Mỹ. Ảnh: WSJ" src="https://i1-giadinh.vnecdn.net/2024/10/16/0a6e64e99b2716ea81d2e42eb3d7b0-5899-1476-1729072762.png?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=7AZ67PhXL8ECvjOKCdIdeQ"></span></span>
<p>Jamie Beaton, 29 tuổi, nhà sáng lập của Crimson Education, trung tâm luyện thi vào đại học hàng đầu Mỹ. Ảnh: <em>WSJ</em></p>
<p>Trong năm nay, gần 2% số ứng viên được nhận vào đại học tại các trường danh tiếng như Brown, Columbia, Harvard và Pennsylvania là học sinh của Beaton. Trong số đó, có 24 học sinh được nhận vào Yale, 34 vào Stanford và 48 vào Cornell. Thư trúng tuyển này đã được công ty kiểm toán PricewaterhouseCoopers xác nhận.</p>
<p>Chi phí dịch vụ của Crimson dao động từ 30.000 đến 200.000 USD cho một chương trình kéo dài 4-6 năm, bao gồm dạy kiến thức học thuật, luyện thi, hướng dẫn cách xin thư giới thiệu và thực hiện các dự án ngoại khóa.</p>
<p>Crimson là công ty hàng đầu trong thị trường tư vấn tuyển sinh đại học Mỹ, nơi các gia đình sẵn sàng bỏ ra số tiền lớn để có lợi thế trong quy trình cạnh tranh khốc liệt này. Doanh thu ngành tư vấn đại học đã tăng gấp ba lần trong 20 năm qua, đạt 2,9 tỷ USD, theo <em>IBISWorld.</em></p>
<p>Hiện có khoảng 10.000 người làm tư vấn đại học toàn thời gian tại Mỹ và 3.000 người làm việc ở nước ngoài.</p>
<p>Beaton sinh ra ở thành phố Auckland, New Zealand. Ngay từ nhỏ anh đã quyết tâm trở thành "học sinh trung học xuất sắc nhất New Zealand".</p>
<p>Chàng trai từng bỏ các hoạt động không thể đạt điểm số cao (piano, quần vợt hay toán) và nổi tiếng khắp đất nước khi chuyển sang các lĩnh vực như hùng biện và kỹ thuật. Beaton cũng thành lập hai doanh nghiệp và làm thêm tại một cửa hàng thức ăn nhanh. Kết quả, anh được 25 đại học danh tiếng mời học, bao gồm cả Harvard, Yale, Princeton và Stanford.</p>
<p>Thành tích của Beaton lan truyền khắp New Zealand. Khi 230 người đến nghe Beaton nói chuyện vào năm cuối trung học, anh nhận ra đây là cơ hội kinh doanh.</p>
<p>Vào đại học năm nhất, Beaton thành lập doanh nghiệp. Anh kết nối với những sinh viên hàng đầu để đồng hành với con cái của các gia đình giàu có. Sau một năm, công ty đã có doanh thu hơn một triệu USD. Sau 11 năm thành lập, Crimson được định giá 554 triệu USD, có 26 văn phòng tại 21 quốc gia và thành lập một trường trung học trực tuyến với 2.000 học sinh. Công ty hiện có 850 nhân viên toàn thời gian và 3.000 gia sư bán thời gian.</p>
<span class="mnl__image__root nml__editor__content__image MuiBox-root css-1d2j38h" node="[object Object]"><span class="mnl__image__wrapper lazy-load-image-background blur lazy-load-image-loaded" style="color: transparent; display: inline-block;"><img class="MuiBox-root css-1d1z4yn" alt="Beaton gặp gỡ giám đốc Beaton trò chuyện với giám đốc cấp cao của Crimson, sau cuộc gặp với các học sinh và cựu học sinh của Crimson hồi tháng 8. Ảnh: WSJ" src="https://i1-giadinh.vnecdn.net/2024/10/16/775115567849d71f30f3fcd901a596-7298-4286-1729072762.png?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=0mPcNi2QFgQTMW_6lWAjLg"></span></span>
<p>Beaton trò chuyện với giám đốc cấp cao của Crimson, sau cuộc gặp với các học sinh và cựu học sinh của hồi tháng 8/2024. Ảnh:<em> WSJ</em></p>
<p>Một số người chỉ trích cho thành công của Crimson bị phóng đại vì nhiều học sinh của họ đã vốn rất xuất sắc. Như Mark Dunn, giám đốc tuyển sinh tại Yale, cho biết việc thuê dịch vụ tư vấn có thể gây bất lợi nếu hồ sơ của học sinh quá "kỹ thuật".</p>
<p>Beaton cho biết thông qua việc kết hợp thông tin về tuyển dụng giảng viên, tỷ lệ giảng viên và sinh viên của từng khoa, cùng với tỷ lệ trúng tuyển theo chuyên ngành họ có thể đưa ra những lời khuyên phù hợp cho học sinh của mình. "Quy trình tuyển sinh cũng giống như huấn luyện thể thao. Bạn có thể luyện tập để cải thiện", anh nói.</p>
<p>Dữ liệu từ hồ sơ của những học sinh được nhận vào Ivy League đã giúp Beaton hiểu rõ hơn những yêu cầu để được tuyển sinh. Ví dụ điểm SAT trung bình của học sinh trúng tuyển vào Ivy League là 1568 - gần như tuyệt đối.</p>
<p>Beaton khuyên học sinh nên tham gia 10 hoạt động ngoại khóa, giữ các vị trí như đội trưởng hoặc chủ tịch câu lạc bộ và vị trí mang tính khởi nghiệp, nên có ít nhất một chủ đề về "công bằng xã hội".</p>
<p>Những thư giới thiệu của giáo viên chỉ "tốt" thôi là chưa đủ. Giáo viên cần nhấn mạnh rằng học sinh là người xuất sắc, tốt nhất trong số những học sinh xuất sắc nhất họ từng dạy. Crimson cung cấp chiến lược để học sinh có được những thư giới thiệu như vậy.</p>
<p>Beaton cho biết khoảng 1/3 học sinh của Crimson đạt được tất cả các tiêu chí này và có cơ hội lớn nhất để được nhận vào các trường đại học hàng đầu. Beaton thích làm việc với học sinh từ năm 11 tuổi để xây dựng kỹ năng học tập và quản lý thời gian trước khi vào cấp ba.</p>
<span class="mnl__image__root nml__editor__content__image MuiBox-root css-1d2j38h" node="[object Object]"><span class="mnl__image__wrapper lazy-load-image-background blur lazy-load-image-loaded" style="color: transparent; display: inline-block;"><img class="MuiBox-root css-1d1z4yn" alt="Beaton và mẹ trong lễ tốt nghiệp Đại học Harvard. Ảnh: WSJ" src="https://i1-giadinh.vnecdn.net/2024/10/16/d8c6be11fb4d9f08b8ccec93c4ad33-1841-9979-1729072762.png?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=kARPOY_6TG5HsoslCr8s2Q"></span></span>
<p>Beaton và mẹ trong lễ tốt nghiệp Đại học Harvard. Ảnh: <em>WSJ</em></p>
<p>Một số gia đình sử dụng dịch vụ của Crimson tỏ ra nhạy cảm khi xuất hiện trên báo chí. Một người cha ở Massachusetts, có con trai lớp 8 đang học với gia sư của Crimson, khen ngợi công ty nhưng yêu cầu không được nêu tên vì không muốn thành tích của con trai bị xem nhẹ.</p>
<p>Daniela Ielceanu cho biết đã thuê Crimson sau một thời gian dài tìm kiếm. Vợ chồng cô vốn được gia đình nuôi dạy với kỳ vọng cao phải học giỏi ở trường và giờ đều là những người thành đạt sống ở Los Gatos, một thị trấn giàu có ở Thung lũng Silicon. Họ muốn thúc đẩy con trai đang học lớp 8 đi xa nhất có thể trên con đường học hành nhưng không phải chịu quá nhiều áp lực.</p>
<p>"Đối với chúng tôi, giáo dục là rất quan trọng", Daniela Ielceanu nói. "Nó đã giúp chúng tôi vượt qua ranh giới giai cấp và cho chúng tôi mọi thứ".</p>`}
      />
    </Box>
  );
}
